### PR TITLE
Rename to LICENSE.txt

### PR DESCRIPTION
**Pull request by wilzbach**
I'm not familiar with VisualD. Are there any scripts depending on this file?
(I couldn't find anything with a quick grep)

### CODE REVIEW

**Comment by rainers** [comment]
It is referenced in the solution and by the NSIS installer.

**Comment by wilzbach** [comment]
OK done. BTW your file header seems to be:

```d
// See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt
```

**Comment by wilzbach** [comment]
Ideas:
- `sed`ing over these files
- symlink
- have two LICENSE files
...

**Comment by rainers** [comment]
Ok, I'll replace them.

**Pull request merged**
