### PR TITLE
Update dbuild project and solution.

### PR DESCRIPTION
**Pull request by bleskodev**
* Fix compilation warnings related to "Embed Interop Types" setting for
referenced dlls.
* Add hint paths for vs2017 professional dlls where applicable.
* Add Debug-v14 and Debug-v15 configurations to solution.

### CODE REVIEW

**Comment by bleskodev** [comment]
This is a small cleanup for project/solution I did while developing multi processor compilation (which works and will be proposed in the separate patch).

**Comment by rainers** [comment]
While this nicely removes the warnings for the v12 and v14 builds, I get an error for v15:
```
1>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): 
warning MSB3277: Found conflicts between different versions of the same dependent assembly 
that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>c:\s\d\visuald\trunk\msbuild\dbuild\CompileD.cs(13,18,13,26): error CS0012: The type 'Microsoft.Build.Utilities.ToolTask' is defined in an assembly that is not referenced. You must 
add a reference to assembly 'Microsoft.Build.Utilities.v12.0, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

The problem seems to be that there is only one hint path, so your additions for the professional version of VS2017 override the community version path. 
I guess we can figure the path with some conditional:
```
<PropertyGroup>
   <VS2017InstallPath Condition="Exists('c:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\PrivateAssemblies\envdte.dll')">c:\Program Files (x86)\Microsoft Visual Studio\2017\Community</VS2017InstallPath>
   <VS2017InstallPath Condition="Exists('c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\PrivateAssemblies\envdte.dll')">c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional</VS2017InstallPath>
</PropertyGroup>
```
but that caused other errors when used within the references. Maybe we have to duplicate the reference section based on the condition above.

**Comment by rainers** [comment]
> while developing multi processor compilation (which works and will be proposed in the separate patch).

That sounds great!

**Comment by bleskodev** [comment]
OK, I'll try to figure out what is happening.
In your situation, you have only community version of VS2017 installed, right?
You are building with VS2013, right?

**Comment by bleskodev** [comment]
I think this should fix the hint path problem. Can you confirm? Thanks!

**Pull request merged**
