### PR TITLE
Fix 'rebuild-all' behaviour after single file change.

### PR DESCRIPTION
**Pull request by bleskodev**
The 'rebuild-all' behaviour was caused by wrong cmd line
generation used when comparing the current build with the previous
build (content of dcompile.command.1.tlog file).

Changes:
* Integrate 'Sources' task parameter to the standard VC tool switches
  (as used by CL or ClangCompile tasks). This allows reuse of the
  standard code for command line generation and excluding 'Sources' from
  command line when necessary (for TLog and out-of-date detection).
  This, however, triggers the introduction of two new overrides:
  ResponseFileEscape() and GetResponseFileSwitch(), needed to bypass
  the 'mandatory' usage of response file when triggering the compilation
  and pass the standard tool switches as command line parameters.
  The response file could probably work for dmd because it supports
  '@' switch, I don't know if this is the case for the other compilers
  (should be probably investigated further).

* Use GenerateCommandLineExceptSwitches() method instead of
  GenerateCommandLineCommands() where appropriate (in
  ConstructCommandTLog() for example) since this is the method which
  is used when building the command line for out-of-date detection.

* Remove addition of sources to the command line in
  GenerateCommandLineCommands() method; this is not needed anymore as it
  is handled by GenerateResponseFileCommandsXXX (called automatically
  by GenerateCommandLineExceptSwitches()). This is also the reason to
  remove call to GenerateResponseFileCommands() in the same function.

* Reorder command line log (in ExecuteTool) to show the command line
  as it will be sent to the compiler (responseFileCommands after
  commandLineCommands).

Potential problems:
* Removed special handling of !TrackFileAccess in
  GenerateCommandLineCommands() method. I don't know in which case this
  code is active.
* Tested only on VS2015 & VS2017 (I have no access to previous versions of VS)

### CODE REVIEW

**Comment by rainers** [comment]
Very cool!

> The response file could probably work for dmd because it supports
> '@' switch, I don't know if this is the case for the other compilers
> (should be probably investigated further).

LDC is currently the only other compiler supported and it supports '@' response files, too.

> Removed special handling of !TrackFileAccess in
> GenerateCommandLineCommands() method. I don't know in which case this
> code is active.

I think TrackFileAccess might be false if no TrackerLogDirectory is passed by dcompile.target, but I don't think it's worth supporting.

> Tested only on VS2015 & VS2017 (I have no access to previous versions of VS)

I tried it on VS2013, too, and it works nicely. Other versions are not supported anyway.

**Comment by rainers** [comment]
@bleskodev Thanks!

**Comment by bleskodev** [comment]
@rainers You're welcome!
Thinking of it, now that I already invested the energy to understand how the whole thing works, it seems to me it would be low energy effort to push the thing a bit further and:
* pass all parameters to standard VC tool switches system; the benefit I see is that the code would (hopefully) become more robust to future changes on the VS side (I think this rebuild bug has been introduced with VS2015; they changed the underlying system and GenerateCommandLineCommands() become obsolete...), this would also allow to remove those two #ifdef-ed implementations (GenerateCommandXXX). Finally, the implementation would be more like CL and ClangCompile tasks (done by MS), which sounds to me like a good thing.
* try to use response files when calling the compiler; this would allow to remove the hack/bypass I needed to add to reconvert response file to command line (again; cleanup)
Do you think such a patch would be of interest to you?

**Comment by rainers** [comment]
@bleskodev I have the impression that you know way more about this than I do. Your suggestions sound reasonable. If they don't break it I'll be happy to merge them. (VS2013 might be a candidate if the underlying system works a bit different - it's probably no longer a main target, though.)

BTW: a preliminary installer with your changes has been built here: https://ci.appveyor.com/project/rainers/visuald/build/job/m0ahf3h173t9kirr/artifacts

**Pull request merged**
